apiVersion: v1
kind: Service
metadata:
  name: {{ include "example.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: hello-world-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer